# Introduction {#introduction}

Findings generated by international research can be widely applicable and relevant to informing and influencing national health policies and decisions (e.g. policies and guidelines relating to COVID-19). However, the most effective and meaningful policies are invariably borne from locally-driven research addressing contextualised health and health system problems.

The Seychelles is one of the few Sub-Saharan African countries with efficient, accurate and comprehensive data collection and disaggregation, across a variety of health metrics within the public health sector. However, critical skills and health research capacity to analyse this data and build a local evidence-base with which to inform policy and improve population health, are severely lacking. This shortcoming risks compromising efforts to meet national strategic health priorities and achieve SDG health targets.

To date, this skills gap has been bridged by outsourcing data analysis to international organisations and/or hiring foreign consultants. This has come at a significant risk of encouraging “parachute” research, whose objectives and findings have not necessarily been applicable to the local context nor aligned with national health agendas.

Recently, driven in part by the vital role data analysis has played and continues to play in the COVID-19 response locally, this critical shortage of data analysis skills has been recognised by the Seychelles Ministry of Health (MOH) as an acute problem, in need of urgent action.

We propose tackling this skills gap and building locally sustainable health research capacity by leveraging the vast research experience and skills of Oxford research partners to train and upskill data analysts from the Ministry of Health (MOH) Seychelles.

A *'tailor-made’* curriculum will be developed and designed based on specific and current research-policy needs already identified by MOH partners. These key areas have been chosen based on impact, priority and what can be feasibly delivered in a 1-month period of intense training.

The topics covered by the training include:

1) Data analysis of health system performance indicators, particularly in health financing - cost-benefit and cost-effectiveness analyses.

2) Training in advanced statistical methods to support ongoing priority research and policy projects, specifically:

    (i) statistical methods for ongoing national vaccine effectiveness studies for COVID-19;
    
    (ii) training in survival analyses for specific diseases (i.e. statistical methods for cancer survival analyses); and,

    (iii) analyses in national mortality trends and surveillance.

The training will be delivered through both online coursework to be completed by all trainees over a 3-week period, followed by one week of intensive on-site training.

This handbook has been developed in support of the **Seychelles-Oxford Partnership Statistics Training** project which aims to strengthen local health research capacity in Seychelles through intensive training in health economic and statistical methods. This collaboration will build capacity for evidence-based health policy-making to better respond to local health challenges. In the long term, this initiative seeks to develop a culture of research in Small Island Developing States (SIDS), often under-represented in global heath research. It is therefore a step towards addressing this imbalance and promoting equitable participation and contribution of SIDS to global health research efforts.
